### ISSUE TITLE
Add support for Electron

### ISSUE THREAD

**Issue by lipis** [bestiejs/platform.js#91] opened 2015-12-15 13:08 UTC
Here is an example from http://electron.atom.io

> Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_1) AppleWebKit/537.36 (KHTML, like Gecko) Wire/2.3.2553 Chrome/45.0.2454.85 **Electron/0.35.2** Safari/537.36

**Comment by d10** [comment] 2016-01-02 14:54
Marking as duplicate of #18.

**Closed by d10** 2016-01-02 14:54 UTC
Labels: duplicate
