### ISSUE TITLE
Unsupported UA for edge (latest version for Mobile)

### ISSUE THREAD

**Issue by mayank30** [bestiejs/platform.js#183] opened 2020-07-01 18:06 UTC
![Screenshot_20200701-233453](https://user-images.githubusercontent.com/6511688/86277025-9e917000-bbf3-11ea-94ff-1e6eae99177e.jpg)

Please find the attached screenshot

**Comment by mayank30** [comment] 2020-07-01 18:06
{
    "name": "Chrome Mobile",
    "version": "77.0.3865.116",
    "layout": "Blink",
    "prerelease": null,
    "os": "Android 10",
    "manufacturer": null,
    "product": null,
    "description": "Chrome Mobile 77.0.3865.116 on Android 10",
    "ua": "Mozilla/5.0 (Linux; Android 10; GM1911) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.116 Mobile Safari/537.36 EdgA/45.05.4.5036"
}

**Comment by bnjmnt4n** [comment] 2020-07-02 11:06
Duplicate of #158. This has been fixed, and a new release should be out sometime this week.

**Closed by bnjmnt4n** 2020-07-02 11:06 UTC
Labels: duplicate

**Comment by mayank30** [comment] 2020-07-02 11:13
Perfect thanks
